import { useState } from "react";
import { api } from "../services/api";

const SCENARIOS = [
  {
    id: "A",
    title: "Scenario A — Genuine Caller",
    description: "Low synthetic probability, high speaker similarity, low context risk.",
    expected: "LOW",
  },
  {
    id: "B",
    title: "Scenario B — Synthetic Caller",
    description: "High synthetic probability, medium context risk (e.g. unfamiliar request).",
    expected: "HIGH",
  },
  {
    id: "C",
    title: "Scenario C — High-Risk Impersonation",
    description:
      "High synthetic probability, speaker mismatch, high-value transaction, urgency, and a bypass request.",
    expected: "CRITICAL",
  },
];

export default function DemoMode() {
  const [analyzeFile, setAnalyzeFile] = useState<File | null>(null);
  const [analysis, setAnalysis] = useState<any>(null);
  const [status, setStatus] = useState("");

  const runAnalysis = async () => {
    if (!analyzeFile) return;
    setStatus("Analyzing uploaded audio...");
    try {
      const res = await api.analyzeAudio(analyzeFile);
      setAnalysis(res);
      setStatus("");
    } catch {
      setStatus("Analysis failed — check the file format (wav/mp3/flac/ogg/m4a).");
    }
  };

  return (
    <div className="space-y-6">
      <header>
        <h1 className="text-xl font-semibold text-slate-100">Demo Mode</h1>
        <p className="text-sm text-slate-500">
          Run the full pipeline locally without telecom integration. Upload real or synthetic
          voice samples, or walk through the three scripted scenarios below. Use only synthetic
          or authorized demo identities — never a real person's voice without consent.
        </p>
      </header>

      <div className="bg-panel border border-panelBorder rounded-xl p-4 space-y-3">
        <h2 className="text-sm font-semibold text-slate-300">Upload &amp; Analyze Audio</h2>
        <input type="file" accept="audio/*" onChange={(e) => setAnalyzeFile(e.target.files?.[0] ?? null)} />
        <button
          onClick={runAnalysis}
          className="bg-accent/10 text-accent border border-accent/40 px-4 py-2 rounded-lg text-sm hover:bg-accent/20"
        >
          Run Detection
        </button>
        {status && <p className="text-sm text-slate-500">{status}</p>}
        {analysis && (
          <div className="text-sm text-slate-300 space-y-1 mt-2">
            <div>Chunks analyzed: {analysis.num_chunks_analyzed}</div>
            <div>Average synthetic probability: {(analysis.average_synthetic_probability * 100).toFixed(1)}%</div>
            <div>Average prosody anomaly: {(analysis.average_prosody_anomaly * 100).toFixed(1)}%</div>
          </div>
        )}
      </div>

      <div className="grid md:grid-cols-3 gap-4">
        {SCENARIOS.map((s) => (
          <div key={s.id} className="bg-panel border border-panelBorder rounded-xl p-4 space-y-2">
            <h3 className="text-sm font-semibold text-slate-200">{s.title}</h3>
            <p className="text-xs text-slate-500">{s.description}</p>
            <p className="text-xs text-slate-400">
              Expected final risk: <span className="font-semibold">{s.expected}</span>
            </p>
          </div>
        ))}
      </div>

      <p className="text-xs text-slate-500">
        Scenario simulation wiring (uploading paired real/synthetic samples and driving them
        through the Live Call Monitoring WebSocket) is generated by{" "}
        <code>scripts/generate_demo_data.py</code> — see the README for how to run it.
      </p>
    </div>
  );
}
